runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  PROJECT_ID: "project-id"  # Reemplaza esto con tu ID de proyecto real

# Configuración de Secret Manager (recomendado para producción)
service_account: "project-id@appspot.gserviceaccount.com"
