runtime: python310  # Especifica la versión correcta de Python
entrypoint: gunicorn -b :8080 main:app

env_variables:
  TELEGRAM_TOKEN: "8016737487:AAErN4WYgVkajp6OSKLtvqAlgamyL0DVQdg"
  OPENAI_API_KEY: "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"
  GOOGLE_CLOUD_PROJECT: "bot-test-455616"

handlers:
  - url: /.*  # Captura todas las rutas
    script: auto  # Deja que el entorno determine el manejador adecuado

instance_class: F2  # Ajusta esto según la carga esperada

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
